import {
    Injectable,
    NestInterceptor,
    ExecutionContext,
    CallHandler,
} from '@nestjs/common';
import { Observable } from 'rxjs';
import { FastifyRequest, FastifyReply } from 'fastify';

@Injectable()
export class RequestIdInterceptor implements NestInterceptor {
    intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
        const ctx = context.switchToHttp();
        const request = ctx.getRequest<FastifyRequest>();
        const response = ctx.getResponse<FastifyReply>();

        // Get request ID from header or use the one generated by Fastify
        const requestId =
            (request.headers['x-request-id'] as string) || request.id;

        // Ensure the request ID is available in headers
        if (!request.headers['x-request-id']) {
            request.headers['x-request-id'] = requestId;
        }

        // Set the request ID in the response header
        response.header('X-Request-ID', requestId);

        return next.handle();
    }
}